package exercise;

/**
 * @author Novin on 07/12/2022
 * @project KelasSwingCrud
 */
public class MyException extends Exception {
    private String teks;
    MyException(String s) {
        teks  = "Exception generated by : " + s;
        System.out.println(teks);
    }
}
class Eksepsi{
    static void tampil(String s) throws Exception{
        System.out.println("Tampil");
        if (s.equals("amir")){
            throw new MyException(s);
        }
        System.out.println("OK!!");
    }

    public static void main(String[] args) {
        try{
            tampil("ali");
            tampil("amir");
        } catch (Exception exception){
            System.out.println("Tangkap : " + exception);
        }
    }
}
